#!/bin/sh
### BEGIN INIT INFO
# Provides:          quadcopter
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop quadcopter.
# /etc/init.d/
# sudo update-rc.d quadcopter defaults
# sudo update-rc.d -f quadcopter remove
### END INIT INFO
#QUADCOPTER_PATH=/data/work/workspace/pi/063.Quadcopter
QUADCOPTER_PATH=/home/pi/work/quadcopter
case $1 in
    start)
        $QUADCOPTER_PATH/shell/quadcopter.sh start
        ;;
    stop)
       $QUADCOPTER_PATH/shell/quadcopter.sh stop
        ;;
    restart)
        $QUADCOPTER_PATH/shell/quadcopter.sh restart
        ;;
*)
echo "Usage: $0 (start|stop|restart)"
;;
esac
